name: simple_orm_generator
description: "simple ORM generator"
version: 1.0.0
authors:
  - liuxiaobo<liuxiaobo19890731@gmail.com>
homepage: https://github.com/liuxb-tofu/SimpleORM/tree/main/generator

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  analyzer: ^6.2.0
  source_gen: ^1.5.0
  build: ^2.0.0
  simple_orm_annotation: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_test: ^2.2.2

