name: simple_orm
description: "simple ORM annotation"
version: 0.0.1
homepage: https://github.com/liuxb-tofu/SimpleORM

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: 2.3.3